# Generated by Django 2.1.7 on 2019-04-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190329_2003'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['name'], 'verbose_name': 'категорию', 'verbose_name_plural': 'категории'},
        ),
    ]
