# Generated by Django 2.1.8 on 2019-04-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190429_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='_activation_key_expires',
            new_name='activation_key_expires',
        ),
    ]
